// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"game_assistantor/debug/go_zero/api_mode/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/info",
				Handler: orderInfoHandler(serverCtx),
			},
		},
	)
}
