// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug/go_zero/protoc_mode/goods.proto

package goods

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//定义请求体
type GoodsRequest struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsRequest) Reset()         { *m = GoodsRequest{} }
func (m *GoodsRequest) String() string { return proto.CompactTextString(m) }
func (*GoodsRequest) ProtoMessage()    {}
func (*GoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e90cd0a07b6790, []int{0}
}

func (m *GoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsRequest.Unmarshal(m, b)
}
func (m *GoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsRequest.Marshal(b, m, deterministic)
}
func (m *GoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsRequest.Merge(m, src)
}
func (m *GoodsRequest) XXX_Size() int {
	return xxx_messageInfo_GoodsRequest.Size(m)
}
func (m *GoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsRequest proto.InternalMessageInfo

func (m *GoodsRequest) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

//定义响应体
type GoodsResponse struct {
	// 商品id
	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	// 商品名称
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsResponse) Reset()         { *m = GoodsResponse{} }
func (m *GoodsResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsResponse) ProtoMessage()    {}
func (*GoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9e90cd0a07b6790, []int{1}
}

func (m *GoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsResponse.Unmarshal(m, b)
}
func (m *GoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsResponse.Marshal(b, m, deterministic)
}
func (m *GoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsResponse.Merge(m, src)
}
func (m *GoodsResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsResponse.Size(m)
}
func (m *GoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsResponse proto.InternalMessageInfo

func (m *GoodsResponse) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *GoodsResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GoodsRequest)(nil), "goods.GoodsRequest")
	proto.RegisterType((*GoodsResponse)(nil), "goods.GoodsResponse")
}

func init() {
	proto.RegisterFile("debug/go_zero/protoc_mode/goods.proto", fileDescriptor_a9e90cd0a07b6790)
}

var fileDescriptor_a9e90cd0a07b6790 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x49, 0x4d, 0x2a,
	0x4d, 0xd7, 0x4f, 0xcf, 0x8f, 0xaf, 0x4a, 0x2d, 0xca, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f,
	0x8e, 0xcf, 0xcd, 0x4f, 0x49, 0xd5, 0x4f, 0xcf, 0xcf, 0x4f, 0x29, 0xd6, 0x03, 0x8b, 0x08, 0xb1,
	0x82, 0x39, 0x4a, 0x9a, 0x5c, 0x3c, 0xee, 0x20, 0x46, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89,
	0x90, 0x24, 0x17, 0x07, 0x58, 0x22, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88,
	0x1d, 0xcc, 0xf7, 0x4c, 0x51, 0xb2, 0xe3, 0xe2, 0x85, 0x2a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0xc5, 0xa3, 0x56, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x33, 0x08, 0xcc, 0x36, 0xb2, 0xe3, 0x62, 0x05, 0xeb, 0x17, 0x32, 0xe5, 0xe2, 0x48, 0x4f, 0x2d,
	0x81, 0xb0, 0x85, 0xf5, 0x20, 0x8e, 0x42, 0x76, 0x84, 0x94, 0x08, 0xaa, 0x20, 0xc4, 0x3a, 0x27,
	0xce, 0x28, 0x76, 0x3d, 0x88, 0x17, 0x92, 0xd8, 0xc0, 0x7e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x25, 0x1b, 0xfb, 0x62, 0xec, 0x00, 0x00, 0x00,
}
